### ISSUE TITLE
The install_requires in setup.py does not take effect.

### ISSUE THREAD

**Issue by shinux** [bottlepy/bottle-werkzeug#10]
`bottle-werkzeug` would not check any requires of my python package. whatever in global or in a virtual environment.

`werkzeug` and `bottle` would not be installed even they don't exist in environment.

it just installed the single package itself.

**Comment by xudeheng** [comment]
How to run with werkzeug?

**Comment by shinux** [comment]
用这个库就可以了呀。

**Comment by defnull** [comment]
Fixed in `0.1.1`.

**Comment by dehengxu** [comment]
误解，以为这个把 werkzeug 作为 wsgi server 来用的。

**Comment by defnull** [comment]
Please speak English.
